all:
	npm install nodemailer
	npm install nodemailer-dkim
	npm install express
	npm install ws
	npm install password-hash
	npm install mysql
	npm install randomstring
	npm install marked

clean:
	- rm -rf node_modules
