#!/usr/bin/env python

import os
import sys
import subprocess

print('Enter a user email:')
email = raw_input()

# open the mysql connection process
sql_process = subprocess.Popen(['mysql', '-u', 'root', '-p', 'UniSecrets'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
sql = 'INSERT INTO `moderator`(`email`) VALUES ("{}");'.format(email)
p_out, p_err = sql_process.communicate(input=sql)
print(p_out)
print(p_err)
